apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}
spec:
  selector:
    app: ${project.artifactId}
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  selector:
    matchLabels:
      app: ${project.artifactId}
  template:
    metadata:
      labels:
        app: ${project.artifactId}
    spec:
      containers:
        - name: ${project.artifactId}
          image: ${app.container.image}
          # this is needed if you wish to pull the image from local dummy registry e.g. dev.local/myrepo/myapp
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "32Mi"
              cpu: "10m"
          ports:
            - name: http-web
              containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /
      initContainers:
        - name: build-status-checker
          image: quay.io/rhdevelopers/build-status-checker
          args:
            - poll
            - --buildname=${project.artifactId}-build
      serviceAccountName: build-bot
