apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: build-reader
rules:
  - apiGroups:
      - build.knative.dev
    resources:
      - builds
    verbs:
      - get
      - list
      - view
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: build-reader
subjects:
  - kind: ServiceAccount
    name: build-bot
